import { Product, Category, Collection, Review, Banner } from "@/types";

/* ============================================
   Mock Data — Zaaforia Premium Fashion
   ============================================ */

// Placeholder images using solid color gradients as URLs
// In production these would come from Cloudinary CDN
const IMG = {
  hero1: "https://images.unsplash.com/photo-1469334031218-e382a71b716b?w=1920&q=80",
  hero2: "https://images.unsplash.com/photo-1490481651871-ab68de25d43d?w=1920&q=80",
  hero3: "https://images.unsplash.com/photo-1441986300917-64674bd600d8?w=1920&q=80",
  
  product1: "https://images.unsplash.com/photo-1595777457583-95e059d581b8?w=600&q=80",
  product2: "https://images.unsplash.com/photo-1566174053879-31528523f8ae?w=600&q=80",
  product3: "https://images.unsplash.com/photo-1515886657613-9f3515b0c78f?w=600&q=80",
  product4: "https://images.unsplash.com/photo-1539008835657-9e8e9680c956?w=600&q=80",
  product5: "https://images.unsplash.com/photo-1496747611176-843222e1e57c?w=600&q=80",
  product6: "https://images.unsplash.com/photo-1502716119720-b23a1e3b8c5d?w=600&q=80",
  product7: "https://images.unsplash.com/photo-1509631179647-0177331693ae?w=600&q=80",
  product8: "https://images.unsplash.com/photo-1485968579580-b6d095142e6e?w=600&q=80",

  cat1: "https://images.unsplash.com/photo-1558618666-fcd25c85f82e?w=600&q=80",
  cat2: "https://images.unsplash.com/photo-1583396082781-f0e97c25b3c8?w=600&q=80",
  cat3: "https://images.unsplash.com/photo-1551803091-e20673f15770?w=600&q=80",
  cat4: "https://images.unsplash.com/photo-1594938298603-c8148c4dae35?w=600&q=80",
  cat5: "https://images.unsplash.com/photo-1567401893414-76b7b1e5a7a5?w=600&q=80",

  col1: "https://images.unsplash.com/photo-1558171813-4c088753af8f?w=800&q=80",
  col2: "https://images.unsplash.com/photo-1509631179647-0177331693ae?w=800&q=80",
  col3: "https://images.unsplash.com/photo-1469334031218-e382a71b716b?w=800&q=80",

  avatar1: "https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=100&q=80",
  avatar2: "https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=100&q=80",
  avatar3: "https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=100&q=80",

  insta1: "https://images.unsplash.com/photo-1509631179647-0177331693ae?w=400&q=80",
  insta2: "https://images.unsplash.com/photo-1515886657613-9f3515b0c78f?w=400&q=80",
  insta3: "https://images.unsplash.com/photo-1496747611176-843222e1e57c?w=400&q=80",
  insta4: "https://images.unsplash.com/photo-1485968579580-b6d095142e6e?w=400&q=80",
  insta5: "https://images.unsplash.com/photo-1539008835657-9e8e9680c956?w=400&q=80",
  insta6: "https://images.unsplash.com/photo-1566174053879-31528523f8ae?w=400&q=80",
};

export const banners: Banner[] = [
  {
    id: "1",
    title: "The Luxury Edit",
    subtitle: "Curated pieces for the modern woman who defines elegance",
    image: IMG.hero1,
    cta: "Explore Collection",
    link: "/shop",
  },
  {
    id: "2",
    title: "Modern Muse",
    subtitle: "Where contemporary meets timeless sophistication",
    image: IMG.hero2,
    cta: "Shop Now",
    link: "/shop",
  },
  {
    id: "3",
    title: "Soft Glam",
    subtitle: "Effortless beauty in every thread",
    image: IMG.hero3,
    cta: "Discover More",
    link: "/collections",
  },
];

export const products: Product[] = [
  {
    id: "1",
    name: "Ivory Silk Drape Dress",
    price: 12999,
    originalPrice: 16999,
    images: [IMG.product1, IMG.product2],
    category: "Dresses",
    tags: ["silk", "luxury", "new"],
    sizes: ["XS", "S", "M", "L", "XL"],
    colors: ["Ivory", "Champagne", "Rose"],
    rating: 4.8,
    reviewCount: 124,
    description: "A stunning silk drape dress that embodies quiet luxury. Crafted from premium mulberry silk with a fluid drape that moves gracefully with every step.",
    isNew: true,
    isFeatured: true,
    stock: 25,
  },
  {
    id: "2",
    name: "Espresso Tailored Blazer",
    price: 8999,
    images: [IMG.product2, IMG.product3],
    category: "Blazers",
    tags: ["tailored", "premium", "trending"],
    sizes: ["S", "M", "L", "XL"],
    colors: ["Espresso", "Noir", "Camel"],
    rating: 4.9,
    reviewCount: 89,
    description: "Impeccably tailored blazer in rich espresso. Structured shoulders meet a relaxed silhouette for the perfect power-feminine balance.",
    isTrending: true,
    isFeatured: true,
    stock: 18,
  },
  {
    id: "3",
    name: "Rose Gold Pleated Skirt",
    price: 6499,
    originalPrice: 8999,
    images: [IMG.product3, IMG.product4],
    category: "Skirts",
    tags: ["pleated", "elegant", "sale"],
    sizes: ["XS", "S", "M", "L"],
    colors: ["Rose Gold", "Silver", "Champagne"],
    rating: 4.7,
    reviewCount: 67,
    description: "Flowing pleated midi skirt with a luxurious metallic sheen. The micro-pleats create a mesmerizing movement that catches light beautifully.",
    isNew: true,
    stock: 32,
  },
  {
    id: "4",
    name: "Champagne Satin Blouse",
    price: 5499,
    images: [IMG.product4, IMG.product5],
    category: "Tops",
    tags: ["satin", "elegant", "bestseller"],
    sizes: ["XS", "S", "M", "L", "XL"],
    colors: ["Champagne", "Ivory", "Blush"],
    rating: 4.6,
    reviewCount: 203,
    description: "Luxuriously soft satin blouse with a relaxed fit. The champagne hue adds warmth while the fabric drapes with effortless elegance.",
    isTrending: true,
    stock: 45,
  },
  {
    id: "5",
    name: "Noir Cashmere Wrap",
    price: 15999,
    images: [IMG.product5, IMG.product6],
    category: "Outerwear",
    tags: ["cashmere", "premium", "winter"],
    sizes: ["One Size"],
    colors: ["Noir", "Ivory", "Grey"],
    rating: 4.9,
    reviewCount: 56,
    description: "Pure cashmere wrap in deepest noir. Incredibly soft and warm, this piece transitions seamlessly from day to evening.",
    isFeatured: true,
    stock: 12,
  },
  {
    id: "6",
    name: "Dusty Rose Linen Set",
    price: 9999,
    originalPrice: 13999,
    images: [IMG.product6, IMG.product7],
    category: "Sets",
    tags: ["linen", "summer", "co-ord"],
    sizes: ["XS", "S", "M", "L"],
    colors: ["Dusty Rose", "Sage", "Sand"],
    rating: 4.8,
    reviewCount: 145,
    description: "A perfectly coordinated linen set in romantic dusty rose. Relaxed yet refined, ideal for elevated casual moments.",
    isNew: true,
    isTrending: true,
    stock: 28,
  },
  {
    id: "7",
    name: "Gold Embroidered Lehenga",
    price: 24999,
    images: [IMG.product7, IMG.product8],
    category: "Ethnic",
    tags: ["embroidered", "ethnic", "luxury", "wedding"],
    sizes: ["S", "M", "L", "XL"],
    colors: ["Gold", "Maroon", "Navy"],
    rating: 5.0,
    reviewCount: 34,
    description: "Exquisite gold-embroidered lehenga with intricate zardozi work. A masterpiece of traditional craftsmanship meets modern silhouette.",
    isFeatured: true,
    stock: 8,
  },
  {
    id: "8",
    name: "Pearl Beaded Evening Gown",
    price: 18999,
    originalPrice: 24999,
    images: [IMG.product8, IMG.product1],
    category: "Gowns",
    tags: ["beaded", "evening", "luxury", "special"],
    sizes: ["XS", "S", "M", "L"],
    colors: ["Pearl White", "Blush", "Midnight"],
    rating: 4.9,
    reviewCount: 42,
    description: "Hand-beaded evening gown adorned with freshwater pearls. A red-carpet worthy piece that radiates timeless glamour.",
    isNew: true,
    isFeatured: true,
    stock: 6,
  },
];

export const categories: Category[] = [
  { id: "1", name: "Dresses", slug: "dresses", image: IMG.cat1, productCount: 156 },
  { id: "2", name: "Ethnic Wear", slug: "ethnic-wear", image: IMG.cat2, productCount: 89 },
  { id: "3", name: "Western Wear", slug: "western-wear", image: IMG.cat3, productCount: 234 },
  { id: "4", name: "Accessories", slug: "accessories", image: IMG.cat4, productCount: 178 },
  { id: "5", name: "Footwear", slug: "footwear", image: IMG.cat5, productCount: 92 },
];

export const collections: Collection[] = [
  {
    id: "1",
    name: "The Luxury Edit",
    tagline: "Curated for the discerning woman",
    image: IMG.col1,
    productCount: 24,
    slug: "luxury-edit",
  },
  {
    id: "2",
    name: "Modern Muse",
    tagline: "Contemporary elegance redefined",
    image: IMG.col2,
    productCount: 18,
    slug: "modern-muse",
  },
  {
    id: "3",
    name: "Soft Glam Collection",
    tagline: "Where beauty meets subtlety",
    image: IMG.col3,
    productCount: 32,
    slug: "soft-glam",
  },
];

export const reviews: Review[] = [
  {
    id: "1",
    userName: "Aarohi Sharma",
    avatar: IMG.avatar1,
    rating: 5,
    comment: "Absolutely stunning quality! The silk dress felt incredibly luxurious. Zaaforia has become my go-to for special occasions.",
    date: "2026-04-15",
    productName: "Ivory Silk Drape Dress",
  },
  {
    id: "2",
    userName: "Priya Mehta",
    avatar: IMG.avatar2,
    rating: 5,
    comment: "The attention to detail is remarkable. Every piece I've ordered has exceeded my expectations. True luxury fashion.",
    date: "2026-04-10",
    productName: "Espresso Tailored Blazer",
  },
  {
    id: "3",
    userName: "Ananya Reddy",
    avatar: IMG.avatar3,
    rating: 5,
    comment: "From packaging to the outfit itself, everything screams premium. The gold embroidered lehenga was a showstopper at my sister's wedding!",
    date: "2026-03-28",
    productName: "Gold Embroidered Lehenga",
  },
];

export const instagramImages = [
  IMG.insta1, IMG.insta2, IMG.insta3,
  IMG.insta4, IMG.insta5, IMG.insta6,
];

export const stats = [
  { label: "Premium Products", value: 2500, suffix: "+" },
  { label: "Happy Customers", value: 50000, suffix: "+" },
  { label: "Luxury Collections", value: 120, suffix: "" },
  { label: "Countries Shipped", value: 35, suffix: "+" },
];
